# Generated by Django 5.0.1 on 2024-01-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("UserName", models.TextField(max_length=50)),
                ("Email", models.TextField(max_length=100)),
                ("Password", models.TextField(max_length=255)),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
